### ISSUE TITLE
Necessary setup for Ubuntu

### ISSUE THREAD

**Issue by phiggins** [zenspider/graphics#17]
I don't know if you'd want to add this to the README or whatever, but I thought someone might find this useful. 

To get the current version (1.0.0b5) to install on Ubuntu 15.10 (Wily Werewolf), I had to install the following packages:

```
# apt-get install libsdl-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev
```

**Comment by phiggins** [comment]
#16 got the tests and examples to run successfully.

**Comment by zsoltf** [comment]
Thanks @phiggins

**Comment by zenspider** [comment]
This should be fixed.
