### ISSUE TITLE
INSTALL : Don't know how to build task 'settings.sh'

### ISSUE THREAD

**Issue by JC-LL** [zenspider/graphics#19]
On MACOSX (El Capitan), I got this error during install. graphics_setup.sh : 

...
rm -rf doc
rm -r pkg
rake aborted!
Don't know how to build task 'settings.sh'

That comes from "rake clean package"

**Comment by zenspider** [comment]
Ugh... https://github.com/zenspider/graphics/commit/30dceff29e42a5ad07771651e6a4c2ef64e8e2d1#commitcomment-19046233

**Comment by zenspider** [comment]
This should be fixed. Thanks for the report. Keep 'em comin'.
