### ISSUE TITLE
Blue lines are dim

### ISSUE THREAD

**Issue by JoshCheek** [zenspider/graphics#23]
![blue-not-showing-up](https://cloud.githubusercontent.com/assets/77495/20418619/08542e52-ad15-11e6-80ca-00974f3450f0.gif)

```ruby
require "graphics"

class Clock < Graphics::Simulation
  def initialize
    @radius     = 75
    @num_lines  = 200
    @colors     = [:red, :green, :blue]
    super 200, 200
  end

  def update iteration
    @multiplier = 0.1 * iteration
    @colors.rotate!          if (iteration+1) % 100 == 0
    @draw_line = !@draw_line if (iteration+1) % 50 == 0
  end

  def draw(iteration)
    clear
    @num_lines.times do |index|
      start  = 2 * Math::PI  * index / @num_lines
      finish = start * @multiplier
      x1 = Math.cos(start)  * @radius + w/2
      x2 = Math.cos(finish) * @radius + w/2
      y1 = Math.sin(start)  * @radius + h/2
      y2 = Math.sin(finish) * @radius + h/2
      if @draw_line
        line x1, y1, x2, y2, @colors.first
      else
        rect x1, y1, x2, y2, @colors.first
      end
    end
  end
end

Clock.new.run if $0 == __FILE__
```

**Comment by JoshCheek** [comment]
So, red lines and green lines are bright, and blue rectangle is bright, but blue lines are dim.

**Comment by JoshCheek** [comment]
It's definitely losing blue b/c if I make it white, it shows up yellow. Tried to follow it through the code to see where it was happening, but I'm not good enough. Maybe in the surface's formatter, but I couldn't figure out where that was coming from.

**Comment by zenspider** [comment]
That's so cool! 

@litonico any ideas?

**Comment by zenspider** [comment]
OK. I know what it is, but not why it is only really having an effect on blue:

``` c
DEFINE_SXYXYC(draw_line,    sge_AALine)
```

If I change that to `sge_Line` it draws as bright as green and red. I think it is a perceptual thing more than an actual error because red and green were plenty bright despite being anti-aliased as well. @litonico just gave a talk on color theory at rubyconf that hit upon this but still pretty much goes over my head, so maybe he can chime in.

I can certainly make it so you have both line options with some extra wiring, but I prefer anti-aliased to be the default.

**Comment by litonico** [comment]
The solution comes from @sophiabaldonado, who stepped through the SDL color code with me after I'd spent _hours_ debugging this for my color cube visualization!

There are too few bits per pixel to display the color properly - you may want to call `super` as
`super win_x_size, win_y_size, bits_of_color`. `24`-bit color is probably plenty. I've had problems with weird color transitions when using `8`.

The graphics gem defaults to `0` bits per pixel of color. @zenspider I don't really know the trade-offs for bytes per pixel, but maybe we should raise the default?

Also, super neat simulation!

**Comment by zenspider** [comment]
`0` means "use the current screen settings", no? I can poke at various values to see if it seems to make a difference.

**Comment by zenspider** [comment]
more data: 0 == 32. Even 31 seems to work fine (guessing they floor to nearest 8).

**Comment by zenspider** [comment]
So, the easiest workaround for this is to change your super:

```
    super 400, 400, 24
```

I can also wire up a non-anti-aliased line or add an option to turn _off_ anti-aliasing. I want it to default to "on" to ensure prettier drawing by default.

**Comment by JoshCheek** [comment]
Confirming that it works for me with 24 and 31 bits per pixel, but not 32.

**Comment by zenspider** [comment]
I've punted on upgrading to SDL2 to try to see if this is fixed there. I'm no longer convinced it is in libSDL at all. Check this out:

```ruby
class Clock < Graphics::Simulation
  def initialize
    super 400, 400, 32
  end

  def draw iteration
    clear

    12.times do |n|
      angle 100, 100, 30*n, 50, :red
      angle 200, 200, 30*n, 50, :green
      angle 300, 300, 30*n, 50, :blue
    end
  end
end

Clock.new.run if $0 == __FILE__
```

**Comment by zenspider** [comment]
![screen shot 2016-11-28 at 13 55 00](https://cloud.githubusercontent.com/assets/9832/20687726/7e0bb1aa-b572-11e6-8534-0489c7c40bd9.png)

vs

![screen shot 2016-11-28 at 13 55 08](https://cloud.githubusercontent.com/assets/9832/20687734/836a7078-b572-11e6-8578-91c4417e9fe6.png)

**Comment by zenspider** [comment]
I think it might be in sge... I'm going to do a walkthrough to see if there is something obvious.

**Comment by zenspider** [comment]
Ugh. Machine architectures...

```diff
  R = ((dc & Rmask) + (( (color & Rmask) - (dc & Rmask) ) * alpha >> 8)) & Rmask;
  G = ((dc & Gmask) + (( (color & Gmask) - (dc & Gmask) ) * alpha >> 8)) & Gmask;
- B = ((dc & Bmask) + (( (color & Bmask) - (dc & Bmask) ) * alpha >> 8)) & Bmask;
+ // need to do different shifting here to avoid overflow
+ B = ((dc & Bmask) + ((((color & Bmask) - (dc & Bmask)) >> 8) * alpha)) & Bmask;
```

**Comment by zenspider** [comment]
![screen shot 2016-11-28 at 15 07 31](https://cloud.githubusercontent.com/assets/9832/20689907/6e097486-b57c-11e6-916c-ee278e97843b.png)

**Comment by zenspider** [comment]
![screen shot 2016-11-28 at 15 08 18](https://cloud.githubusercontent.com/assets/9832/20689930/84b5db2a-b57c-11e6-8a0f-108710f5a3e9.png)

**Comment by zenspider** [comment]
I believe this to be fixed. Not happy with the math, but it's there.

**Comment by litonico** [comment]
The fix is awesome, I'm glad you got that sorted!
but do the horizontal/vertical red and green lines look red and green against a white ground, but the rest look cyan and magenta? Doesn't happen against the black.

Could by my imagination, or could be my eyes are broken after staring at the color cube for so long 👓

**Comment by JoshCheek** [comment]
Yeah, that fixed the blue for me on 32 BPP mode.

Alpha is still not responding. Note that it's not responding on `rect` or `point`, eitiher. Alpha also doesn't work on 24 bpp, though there is code in there to support it. Alpha is handled differently from all the other channels, it gets passed in as its own arg. I assume it's available because I assume anti aliasing uses it, but I'm not able to come up with an example that shows any alpha.

```ruby
require "graphics"

drawing = Graphics::Drawing.new 110, 30, 32
drawing.color.default_proc = -> h, k { k }

swatch = -> x, amount do
  color = drawing.screen.format.map_rgba(255, 255, amount, amount)
  drawing.rect x, 10, 10, 10, color, true
end

swatch[10, 0]
swatch[30, 0.5]
swatch[50, 1]
swatch[70, 128]
swatch[90, 255]

drawing.run
```

**Comment by zenspider** [comment]
No no no @JoshCheek... You know better. File a new issue

**Comment by zenspider** [comment]
@litonico you are correct. 0, 45, and 90 are treated special and not antialiased. Look at the code above this patch for an early return.
