### ISSUE TITLE
Alpha is always opaque

### ISSUE THREAD

**Issue by JoshCheek** [zenspider/graphics#26]
Per [suggestion](https://github.com/zenspider/graphics/issues/23#issuecomment-263719365) I'm moving [this](https://github.com/zenspider/graphics/issues/23#issuecomment-263583388) comment to a new issue :P  Note that [this](https://github.com/zenspider/graphics/issues/23#issuecomment-263423973) diff was applied locally.

```diff
  R = ((dc & Rmask) + (( (color & Rmask) - (dc & Rmask) ) * alpha >> 8)) & Rmask;
  G = ((dc & Gmask) + (( (color & Gmask) - (dc & Gmask) ) * alpha >> 8)) & Gmask;
- B = ((dc & Bmask) + (( (color & Bmask) - (dc & Bmask) ) * alpha >> 8)) & Bmask;
+ // need to do different shifting here to avoid overflow
+ B = ((dc & Bmask) + ((((color & Bmask) - (dc & Bmask)) >> 8) * alpha)) & Bmask;
```

-----

Alpha is still not responding (it's always fully opaque). Note that it's not responding on `rect` or `point`, eitiher. Alpha also doesn't work on 24 bpp, though there is code in there to support it. Alpha is handled differently from all the other channels, it gets passed in as its own arg. I assume it works in general, because I assume anti aliasing uses it, but I couldn't think of an example that would make it obvious. The one below shows that it is always opaque.

![screenshot 2016-11-29 16 50 41](https://cloud.githubusercontent.com/assets/77495/20732370/0486701c-b654-11e6-98e1-ec770471a87f.png)

```ruby
require "graphics"

side    = 100
alphas  = [0, 0.5, 1, 128, 255]
drawing = Graphics::Drawing.new alphas.length*1.5*side+side/2, side*2, 32
drawing.color.default_proc = -> h, k { k }

alphas.each_with_index do |alpha, i|
  color = drawing.screen.format.map_rgba(255, 255, 255, alpha)
  drawing.rect i*1.5*side+side/2, side/2, side, side, color, true
  drawing.text alpha.to_s, i*1.5*side+side/2, 1.5*side, :white
end

drawing.run
```

**Comment by zenspider** [comment]
from https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlfillrect.html

> The color should be a pixel of the format used by the surface, and can be generated by the SDL_MapRGB or SDL_MapRGBA functions. If the color value contains an alpha value then the destination is simply "filled" with that alpha information, no blending takes place.

But I'm also using SGE, so I'll poke in there as well.

This would definitely be one area where upgrading to SDL 2 would be worth it in the long run... But DAMN is it poorly documented and shitty.

**Comment by zenspider** [comment]
It also appears that `map_rgba` is dropping the alpha values entirely. I'm poking to see if I'm initializing something incorrectly.

**Comment by zenspider** [comment]
PAINFULLY reworking some of this stuff... I've got some wierd blending going on. Dunno why alpha blend `0` of red on white results in yellow, but alpha blend `1` doesn't:

![screen shot 2016-11-29 at 20 32 27](https://cloud.githubusercontent.com/assets/9832/20739836/142d2c30-b673-11e6-8172-af559c5b77dc.png)

**Comment by zenspider** [comment]
OK... my blue fix is the problem.

![screen shot 2016-11-29 at 20 37 26](https://cloud.githubusercontent.com/assets/9832/20739903/ab8a4874-b673-11e6-8c40-dd265b14cdf4.png)

**Comment by zenspider** [comment]
```ruby
require "graphics"

class Bug026 < Graphics::Simulation
  def initialize
    super 400, 300, 32


    register_color :b0, 255, 0, 0, 0
    register_color :b1, 255, 0, 0, 1
    register_color :b2, 255, 0, 0, 128
    register_color :b3, 255, 0, 0, 255
  end

  def draw iteration
    clear

    rect 50, 100, 300, 50, :white, :filled

    rect 75, 50, 50, 150,  :b0, :filled
    rect 150, 50, 50, 150, :b1, :filled
    rect 225, 50, 50, 150, :b2, :filled
    rect 300, 50, 50, 150, :b3, :filled

    # self.done = true
  end
end

Bug026.new.run if $0 == __FILE__
```

**Comment by zenspider** [comment]
this is fixed for your _immediate_ problem, but requires reworking basically all of the drawing primitives.

**Comment by zenspider** [comment]
This is handled, yes?

**Comment by JoshCheek** [comment]
It's fixed on Github, but not in the released gem.

**Comment by zenspider** [comment]
Kk. I'm gonna close this. I'm not *too* far from a release? I don't think? I dunno. I'm mentarbating a bit on some of the color stuffs.
