### ISSUE TITLE
Possibly useful SDL2 reference

### ISSUE THREAD

**Issue by JoshCheek** [zenspider/graphics#27]
[OptCarrot](https://github.com/mame/optcarrot/tree/8c5462c7103e78494697311112e24ded0859528b) is the Ruby NES emulator being used as a benchmark for Ruby3x3 (the goal to make MRI 3x faster by v3.0). It interacts with SDL2 through FFI. Not sure if it's useful or not, but figured I'd bring it up. Files are in [this](https://github.com/mame/optcarrot/blob/8c5462c7103e78494697311112e24ded0859528b/lib/optcarrot/driver/sdl2.rb) dir. Here's a screenshot:

![screenshot 2016-12-01 12 35 35](https://cloud.githubusercontent.com/assets/77495/20807233/b34cc43c-b7c3-11e6-84b4-e5bcd613d999.png)

**Comment by zenspider** [comment]
THIS IS DONE!!
