### ISSUE TITLE
Alpha not preserved when blitting

### ISSUE THREAD

**Issue by JoshCheek** [zenspider/graphics#28]
This may be related to #26 

In this code, there is alpha around the dots, I assume this is anti aliasing. When I blit them, it doesn't blend the alpha with the new background, so there are artifacts around the dots that almost look like an outline.

![screenshot 2016-12-09 11 48 33](https://cloud.githubusercontent.com/assets/77495/21059221/03080df8-be07-11e6-9c3f-9e09bd177f76.png)

```ruby
# encoding: utf-8
require 'graphics'
require 'pp'

class MySim < Graphics::Simulation
  include Math

  def initialize
    super 800, 600, 32
  end

  def draw(n)
    side     = 2 + n/10.0
    half     = side/2
    radius   = sqrt (w/2)**2 + (h/2)**2
    diameter = 2 * radius

    dots = sprite diameter, diameter do
      (diameter/side).to_i.times do |y|
        xoff = (y%2) * half
        (diameter/side).to_i.times do |x|
          circle x*side+xoff, y*side+half, 0.35*side, :white, true
        end
      end
    end

    clear
    blit dots, w/2, h/2, 0
    blit dots, w/2, h/2, n
  end
end

MySim.new.run
```

**Comment by zenspider** [comment]
Remove the rotated one and compare. I think this is sge doing shitty maths or something

**Comment by zenspider** [comment]
??

**Comment by JoshCheek** [comment]
I don't understand the instruction, if I remove the rotated one then I can't tell, b/c the edges are over a black background

![image](https://user-images.githubusercontent.com/77495/44950028-56d90c00-ae03-11e8-9632-ecac449052eb.png)

Note that when I change the background colour and zoom in, even the first one's edges are incorrect. They have the anti aliasing, but it's blended with black instead of clear.

![screen shot 2018-09-01 at 4 29 13 pm](https://user-images.githubusercontent.com/77495/44950112-15e1f700-ae05-11e8-9789-b4ba062884b4.png)

**Comment by JoshCheek** [comment]
👆 This is on graphics built from GH master branch.

**Comment by zenspider** [comment]
It isn't alpha blending the way I want, but it looks correct to me now (with sdl2 branch).
