### ISSUE TITLE
Missing text_size method

### ISSUE THREAD

**Issue by jgoizueta** [zenspider/graphics#29]
Hi!

I've tried using `Simulation#text_size` but got this problem:

```
.../gems/graphics-1.0.0b6/lib/graphics/simulation.rb:440:in `text_size': undefined method `text_size' for #<SDL::TTF:0x007fde9ca1fb30> (NoMethodError)
```

It seems the code expects fonts to implement that method but it's not present in `SDL::TTF`.

Just FYI, I've checked out this graphics by by adapting a little [test prgram](https://github.com/jgoizueta/test_geo2d) and I'm liking it! In that example you can find a text-rotating function that can be handy.

**Comment by zenspider** [comment]
This is fixed. Thanks!
