### ISSUE TITLE
'graphics' not simply downloadable via rubygems ?

### ISSUE THREAD

**Issue by JC-LL** [zenspider/graphics#31]
Hello

There is something strange with this gem : 

jcll-mac:~ jcll$ gem install graphics
ERROR:  Could not find a valid gem 'graphics' (>= 0) in any repository
ERROR:  Possible alternatives: graphify, graphist, graphit, graphite, graphes

However we clearly see 'graphics' listed in rubygems.org (1.0.0b6 2016).

JCLL

**Comment by zenspider** [comment]
It's still in beta (until I figure out the color system—hopefully tonight) so you need `--dev`
