### ISSUE TITLE
hline and vline have each other's defaults for the endpoints

### ISSUE THREAD

**Issue by JoshCheek** [zenspider/graphics#34]
hline and vline have each other's defaults for the endpoints ([here](https://github.com/zenspider/graphics/blob/b58117efff3596a9c986f192c8e9f4837815a1e0/lib/graphics/simulation.rb#L430) and [here](https://github.com/zenspider/graphics/blob/b58117efff3596a9c986f192c8e9f4837815a1e0/lib/graphics/simulation.rb#L437))

It passes the tests because `FakeSimulation`'s width and height are the same ([here](https://github.com/zenspider/graphics/blob/b58117efff3596a9c986f192c8e9f4837815a1e0/test/test_graphics.rb#L9)).

```ruby
require 'graphics'

d1 = Graphics::Drawing.new 400, 300, 0, 'wider than tall'
d1.vline d1.w/2, :red
d1.hline d1.h/2, :white
d1.run

d2 = Graphics::Drawing.new 300, 400, 0, 'taller than wide'
d2.vline d2.w/2, :red
d2.hline d2.h/2, :white
d2.run
```

![image](https://user-images.githubusercontent.com/77495/46708872-6d466480-cc06-11e8-9ccb-917f70635ae1.png)

![image](https://user-images.githubusercontent.com/77495/46708874-720b1880-cc06-11e8-81f9-06a9258e4e66.png)

**Comment by zenspider** [comment]
Confirmed via:

```ruby
class Lines < Graphics::Simulation
  def draw n
    vline 100, :red
    hline 200, :green
  end
end
```

and fixed. Thank you!
