### ISSUE TITLE
--without-webp is an invalid option

### ISSUE THREAD

**Issue by NickSchimek** [zenspider/graphics#38]
## Description

Running `brew install sdl2_image --without-webp` as specified in the [graphics_setup script](https://github.com/zenspider/graphics/blob/master/graphics_setup.sh#L27) for mac OS results in an `invalid option error`.

I use homebrew, but I am not familiar with all the available options, and was unable to find an alternative. The closest option I found was `--ignore-dependencies` which says it is:
```
An unsupported Homebrew development flag to skip installing any dependencies of any kind.
````

`--ignore_dependencies` does not seem to be the right option.

I suppose I could install it with the `webp` dependency, but am curious to know if there is a way to install it using homebrew without that dependency. Does anyone have any insight on this?

**Comment by zenspider** [comment]
Done. Thanks!
