### ISSUE TITLE
Menlo not available for linux users

### ISSUE THREAD

**Issue by sentientmonkey** [zenspider/graphics#5]
The paths and font don't match for linux systems. Not sure what a good universal default is here, but this blows up in creating a new simulation. No idea what happens on Windows (probably catches fire and explodes).

**Comment by zenspider** [comment]
I don't really care about making this work for linux users until we HAVE linux users. Doubly so for windows.

**Comment by sentientmonkey** [comment]
@phiggins - were you able to get this going? I know you're a linux user :smile:

**Comment by phiggins** [comment]
@sentientmonkey It installed, and that's about as far as I got. If you need help debugging I'd be happy to poke at it.

**Comment by zenspider** [comment]
No linux users yet. Closing.
