### ISSUE TITLE
blit blip

### ISSUE THREAD

**Issue by sotoseattle** [zenspider/graphics#6]
Graphics::Simulation#blit is not passing the parameters for scaling factors (xs, ys) down to SDL::Surface.transform_blit, and is instead passing ones (maintaining the scale of the image). Also consider defaulting the angle parameter a° to 0.

**Current Code**:

``` ruby
def blit o, x, y, a°, xs=1, ys=1, opt=0
  SDL::Surface.transform_blit o, screen, -a°, 1, 1, o.w/2, o.h/2, x, h-y, opt
end
```

**Alternative Code**:

``` ruby
def blit o, x, y, a°=0, xs=1, ys=1, opt=0
  SDL::Surface.transform_blit o, screen, -a°, xs, ys, o.w/2, o.h/2, x, h-y, opt
end
```

**Comment by zenspider** [comment]
This is fixed in my (unreleased) version. Should be soon? Maybe? Hopefully?
